spring.application.name=chatbot-backend

#api keys
ai.hugging-face-api-key=${HUGGING_FACE_API_KEY_TEXT_GEN}
ai.cloudflare-api-key=${CLOUDFLARE_API_KEY_IMAGE_GEN}
ai.cloudflare-account-id=2129391bbbc8ef87bf2c057293cd5b12